#!/usr/bin/env bash
./configure --prefix='/usr/local/openresty-1.13.6.2' -j4 --with-http_iconv_module \
    --with-http_postgres_module \
    --build='openresty-1.13.6.2 achilles_xushy' \
    --with-threads \
    --with-http_v2_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_image_filter_module=dynamic \
    --with-http_perl_module=dynamic \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gzip_static_module \
    --with-http_auth_request_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_degradation_module \
    --with-http_slice_module \
    --with-http_stub_status_module \
    --with-mail=dynamic \
    --with-mail_ssl_module \
    --with-google_perftools_module \
    --add-dynamic-module='/Users/achilles_xushy/Downloads/openresty/nginx-rtmp-module' \
    --add-dynamic-module='/Users/achilles_xushy/Downloads/openresty/ngx_http_geoip2_module' \
    --add-dynamic-module='/Users/achilles_xushy/Downloads/openresty/nchan-master' \
    --with-cc-opt='-I/usr/local/opt/openssl/include -I/usr/local/opt/pcre/include -I/usr/local/opt/zlib/include' \
    --with-ld-opt='-L/usr/local/opt/openssl/lib -L/usr/local/opt/pcre/lib -L/usr/local/opt/zlib/lib'